# NumPy Fundamentals

Name: Prashanth B

In [1]:
import numpy as np

# Creating Numpy Arrays

In [4]:
#Integer array
A1 = np.array([1,2,3,4,5])
A1

array([1, 2, 3, 4, 5])

In [7]:
A1.shape

(5,)

In [10]:
A1.ndim

1

In [11]:
A1.size

5

In [12]:
A1.dtype

dtype('int64')

In [8]:
#Floating point array
A2 = np.array([1.0, 2, 3, 4, 5])
A2

array([1., 2., 3., 4., 5.])

In [13]:
A2.dtype

dtype('float64')

In [6]:
#Array type checking
print(type(A1))
print(type(A2))
print(type(A1[0]))
print(type(A2[0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.float64'>


In [15]:
#Create a length-10 integer array filled with zeros
print("Integer zero array:", np.zeros(10, dtype=int))

Integer zero array: [0 0 0 0 0 0 0 0 0 0]


In [16]:
#Create a length-10 float array filled with zeros
print("Float zero array:", np.zeros(10))

Float zero array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
#create a 3x5 float array filled with ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#create a 3x5 float array filled with ones
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
#create a 3x5 array filled with 3.2
np.full((3,5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

In [20]:
'''Create an array filled with a linear sequence
stating at 0, ending at 20, stepping by 2
this is similar to built in range() function'''
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
#Create an array of 5 values evenly spaced bw 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
'''Create a 3x3 array of uniformly distributed
random values between 0 and 1'''
np.random.random((3,3))

array([[0.85390143, 0.718983  , 0.01595241],
       [0.01872831, 0.76680702, 0.1820371 ],
       [0.32254755, 0.320108  , 0.61610166]])

In [23]:
'''Create a 3x3 array of normally distributed random values
with mean = 0 and standard deviation = 1'''
np.random.normal(0, 1, (3,3))

array([[ 0.17034957,  0.41664934,  0.38878918],
       [ 0.22847592,  0.550531  ,  1.33355785],
       [ 2.66481741,  0.84417755, -1.05700613]])

In [24]:
#Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[0, 0, 1],
       [6, 5, 1],
       [4, 2, 6]])

In [25]:
#Create a 3x3 identity matrix
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
#Create an uninitialized array of three floats
#the values will be whatever happens to already exist at that memory location
print(np.empty(9))
print(np.empty(3))
print(np.empty((1,4)))
print(np.empty((3,4)))

[ 0.17034957  0.41664934  0.38878918  0.22847592  0.550531    1.33355785
  2.66481741  0.84417755 -1.05700613]
[0.  0.5 1. ]
[[0.25 0.5  0.75 1.  ]]
[[1.6360537e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]


# Array Indexing, Slicing and Accessing

In [32]:
np.random.seed(0)
x1 = np.random.randint(10, size = (3, 4))
x1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [33]:
x1[0]

array([5, 0, 3, 3])

In [34]:
x1[-1]

array([2, 4, 7, 6])

In [35]:
x1[0,0]

5

In [36]:
x1[0][0]

5

In [37]:
x1[1,1]

9

In [38]:
x1[1][1]

9

In [39]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[:5] #first 5 elements

array([0, 1, 2, 3, 4])

In [41]:
x[5:] #last 5 elements(after index 5)

array([5, 6, 7, 8, 9])

In [42]:
x[4:7] #mid subarray

array([4, 5, 6])

In [43]:
x[::2]

array([0, 2, 4, 6, 8])

In [44]:
x[1::2]

array([1, 3, 5, 7, 9])

In [45]:
x[::-1] #reverse order

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
x[5::-2]

array([5, 3, 1])

In [47]:
x1[:2, :3] #two rows, three columns

array([[5, 0, 3],
       [7, 9, 3]])

In [48]:
x1[1:3, 1:4]

array([[9, 3, 5],
       [4, 7, 6]])

In [49]:
x1[::-1, ] #rows reversed

array([[2, 4, 7, 6],
       [7, 9, 3, 5],
       [5, 0, 3, 3]])

In [50]:
x1[:, ::-1] #Columns reversed

array([[3, 3, 0, 5],
       [5, 3, 9, 7],
       [6, 7, 4, 2]])

In [51]:
x1[::-1, ::-1] #both rows and columns reversed

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]])

In [52]:
x1[:, 0] #first column of x1

array([5, 7, 2])

Sub Arrays

In [54]:
#sub arrays has no copy views
x1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [55]:
x1_sub = x1[:2, :2] #slice and get subarray
x1_sub

array([[5, 0],
       [7, 9]])

In [58]:
x1_sub[0,0] = -1 #modify the subarray
x1_sub

array([[-1,  0],
       [ 7,  9]])

In [59]:
x1 #original array also changed

array([[-1,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

In [60]:
#To avoid the above step use copy() function
x1_sub_copy = x1[:2, :2].copy()
x1_sub_copy

array([[-1,  0],
       [ 7,  9]])

In [61]:
x1_sub_copy[0,0] = 42
x1_sub_copy

array([[42,  0],
       [ 7,  9]])

In [62]:
x1

array([[-1,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

# Reshape, Concatenate, Stack and Split

In [63]:
x = np.arange(0, 4)
x

array([0, 1, 2, 3])

In [64]:
x.reshape((2,2))

array([[0, 1],
       [2, 3]])

In [65]:
x.reshape((1,4)) #row vector via reshape

array([[0, 1, 2, 3]])

In [66]:
x[np.newaxis, :] #row vector via newaxis

array([[0, 1, 2, 3]])

In [67]:
x.reshape((4,1)) #column vector via reshape

array([[0],
       [1],
       [2],
       [3]])

In [68]:
x[:, np.newaxis] #column vector via newaxis

array([[0],
       [1],
       [2],
       [3]])

In [69]:
x = np.array([1,2,3,4])
y = np.array([3,4,5,6])
z = np.array([5,6,7,8])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 7, 8])

In [70]:
x1 = x.reshape([2,2])
x1

array([[1, 2],
       [3, 4]])

In [71]:
np.concatenate([x1,x1])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [72]:
np.concatenate([x1,x1], axis=1) #concatenate along the second axis

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [73]:
np.vstack([x,y]) #vertical stack

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [74]:
np.hstack([x,y]) #horizontal stack

array([1, 2, 3, 4, 3, 4, 5, 6])

In [76]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7 8 9]


In [78]:
y = np.arange(16).reshape((4,4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
upper_half, lower_half = np.vsplit(y, [2])
print(upper_half)
print(lower_half)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [80]:
left_half, right_half = np.hsplit(y, [2])
print(left_half)
print(right_half)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Universal functions (Ufuncs)

In [81]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [82]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [83]:
np.add(x, 2)

array([2, 3, 4, 5])

In [84]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [85]:
np.negative(x)

array([ 0, -1, -2, -3])

In [86]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [87]:
np.divide(x, 2)

array([0. , 0.5, 1. , 1.5])

In [88]:
np.floor_divide(x, 2)

array([0, 0, 1, 1])

In [89]:
np.power(x, 2)

array([0, 1, 4, 9])

In [90]:
np.mod(x, 2) #remainders

array([0, 1, 0, 1])

In [91]:
y = np.array([-1, 2, 3])
y

array([-1,  2,  3])

In [92]:
np.absolute(y)

array([1, 2, 3])

In [93]:
np.absolute(y[0])

1

In [94]:
#Trigonometric functions
theta = np.linspace(0,np.pi,3) #divide 0 to pi into 3 parts i.e., 0, pi/2 amd pi
print("theta=", theta)
print("sin_theta=", np.sin(theta))
print("cos_theta=", np.cos(theta))
print("tan_theta=", np.tan(theta))

theta= [0.         1.57079633 3.14159265]
sin_theta= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos_theta= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan_theta= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [95]:
#inverse trigonometric functions
x = [-1, 0, 1]
print("x =", x)
print("arcsin(x) =", np.arcsin(x))

x = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]


In [96]:
#Specifying output
x = np.arange(5)
print(x)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


In [97]:
y = np.zeros(10)
np.power(2, x, out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [98]:
#Aggregates
x = np.arange(1,6)
print(x)
np.add.reduce(x) #Reducing an array to a scalar, here summing all elements

[1 2 3 4 5]


15

In [99]:
np.multiply.reduce(x)

120

In [100]:
np.add.accumulate(x) #store all the intermediate results

array([ 1,  3,  6, 10, 15])

In [101]:
small_array = np.random.random(100)
small_array

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  , 0.96366276,
       0.38344152, 0.79172504, 0.52889492, 0.56804456, 0.92559664,
       0.07103606, 0.0871293 , 0.0202184 , 0.83261985, 0.77815675,
       0.87001215, 0.97861834, 0.79915856, 0.46147936, 0.78052918,
       0.11827443, 0.63992102, 0.14335329, 0.94466892, 0.52184832,
       0.41466194, 0.26455561, 0.77423369, 0.45615033, 0.56843395,
       0.0187898 , 0.6176355 , 0.61209572, 0.616934  , 0.94374808,
       0.6818203 , 0.3595079 , 0.43703195, 0.6976312 , 0.06022547,
       0.66676672, 0.67063787, 0.21038256, 0.1289263 , 0.31542835,
       0.36371077, 0.57019677, 0.43860151, 0.98837384, 0.10204481,
       0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077,
       0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295,
       0.19658236, 0.36872517, 0.82099323, 0.09710128, 0.83794491,
       0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552,
       0.73926358, 0.03918779, 0.28280696, 0.12019656, 0.29614

In [102]:
#Computation time
%timeit sum(small_array)
%timeit np.sum(small_array) #efficient

10.3 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.67 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [103]:
#Multi dimensionnal aggregates
M = np.random.random((3,4))
M

array([[0.24875314, 0.57615733, 0.59204193, 0.57225191],
       [0.22308163, 0.95274901, 0.44712538, 0.84640867],
       [0.69947928, 0.29743695, 0.81379782, 0.39650574]])

In [104]:
np.sum(M)

6.6657887969689655

In [105]:
np.min(M, axis = 0)

array([0.22308163, 0.29743695, 0.44712538, 0.39650574])

In [106]:
np.max(M, axis = 0)

array([0.69947928, 0.95274901, 0.81379782, 0.84640867])

In [107]:
np.min(M, axis = 1)

array([0.24875314, 0.22308163, 0.29743695])

In [108]:
np.max(M, axis = 1)

array([0.59204193, 0.95274901, 0.81379782])

In [109]:
data = np.random.randint(172, 185, size=20)
data

array([180, 172, 180, 177, 181, 172, 184, 181, 178, 177, 175, 173, 180,
       172, 176, 183, 183, 181, 178, 177])

In [110]:
data.mean() #mean

178.0

In [111]:
data.std() #std deviation

3.7013511046643495

In [112]:
data.min() #min value

172

In [113]:
data.max() #max value

184

In [114]:
np.percentile(data, 25) #25th percentile

175.75

In [115]:
np.percentile(data, 75)

181.0

In [116]:
np.median(data)

178.0

# Computations on Arrays: Broad Casting

In [117]:
m = np.ones((3,3))
m

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [118]:
n = np.arange(3)
n

array([0, 1, 2])

In [119]:
m + n

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [120]:
p = np.arange(3)[:, np.newaxis]
p

array([[0],
       [1],
       [2]])

In [121]:
n + p

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Boolean Operators

In [122]:
'''Boolean Operators
& - np.bitwise_and
| - np.bitwise_or
^ - np.bitwise_xor
~ - np.bitwise_not'''
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
(x > 2) & (x < 4)

array([False, False, False,  True, False, False, False, False, False,
       False])

In [124]:
(x < 2) ^ (x > 2)

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [125]:
~(x < 4)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Fancy Indexing

In [126]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [127]:
indices = [3, 7, 4]
x[indices]

array([71, 86, 60])

In [128]:
indices_1 = np.array([[3,7],
                    [4,5]])
x[indices_1]

array([[71, 86],
       [60, 20]])

Sorting Arrays

In [129]:
x = np.array([2,1,4,3,5])
x

array([2, 1, 4, 3, 5])

In [130]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [131]:
x = np.array([2,1,4,3,5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [132]:
x[i]

array([1, 2, 3, 4, 5])

In [133]:
#sorting along rows and columns
rand = np.random.RandomState(42)
X = rand.randint(0,10,(4,6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [134]:
#sort each columns of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [135]:
#sort each rows of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [136]:
#Partial sorts: Partitioning
x = np.array([7,2,3,1,6,5,4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

Thank you