# TensorFlow Fundamentals

Name: Prashanth B

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
#Finding access to GPU
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
#information about GPU using
!nvidia-smi

Mon Jul 10 07:08:51 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Tensors

In [2]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

Constants and Variables

In [13]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

In [18]:
# unchangeable_tensor[0].assign(5)
# unchangeable_tensor
# #produces error

Shuffling

In [22]:
# Creating a random tensor
random = tf.random.Generator.from_seed(0) # set the seed for reproducibility
random_1 = random.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3544159 ,  0.70454913],
       [ 0.03666191,  0.86918795],
       [ 0.43842274, -0.53439844]], dtype=float32)>

In [34]:
# Shuffling a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [47]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

Other ways to create tensors

In [48]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [49]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

# Numpy and Tensors

In [50]:
import numpy as np

In [51]:
numpy_arr = np.arange(1, 25, dtype=np.int32)
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [52]:
tensor_arr = tf.constant(numpy_arr,  shape=[2, 4, 3])
tensor_arr

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [108]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [109]:
np.array(J), type(J), type(np.array(J))

(array([ 3.,  7., 10.]),
 tensorflow.python.framework.ops.EagerTensor,
 numpy.ndarray)

In [110]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [111]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

Shape, Rank, Size

In [53]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [55]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())
# .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [56]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [57]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
# "-1" means last axis
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [58]:
# Add an extra dimension (to the end)

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
# in Python "..." means "all dimensions prior to"

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [59]:
rank_2_tensor.shape, rank_3_tensor.shape

(TensorShape([2, 2]), TensorShape([2, 2, 1]))

# Tensor Operations

In [60]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [65]:
#OR
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [62]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [66]:
#OR
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [63]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [64]:
#OR
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix Multiplication

In [67]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [69]:
#OR
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Reshape and Transpose

In [70]:
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [71]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [72]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

Dot Product

In [81]:
vec1 = tf.constant([1,2])
vec2 = tf.constant([3,4])
tf.tensordot(vec1, vec2, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

# Tensor Aggregation

In [82]:
X = tf.constant(np.random.randint(low=0, high=100, size=50))
X

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 2, 32, 98, 68,  7,  8, 25, 87, 51, 60, 46, 70, 78, 20,  3, 65, 94,
       34, 60,  8, 22, 74, 22, 10, 77, 59, 11, 99, 48, 40, 88, 29, 90, 67,
       42, 78, 17, 29, 39,  5, 79, 44,  3, 28, 56, 44, 64, 17,  4, 61])>

In [83]:
tf.reduce_min(X)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [84]:
tf.reduce_max(X)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [85]:
tf.reduce_mean(X)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [86]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=int64, numpy=2262>

In [88]:
tf.argmax(X)

<tf.Tensor: shape=(), dtype=int64, numpy=27>

In [93]:
tf.argmin(X)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [103]:
tf.square(X)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([   4, 1024, 9604, 4624,   49,   64,  625, 7569, 2601, 3600, 2116,
       4900, 6084,  400,    9, 4225, 8836, 1156, 3600,   64,  484, 5476,
        484,  100, 5929, 3481,  121, 9801, 2304, 1600, 7744,  841, 8100,
       4489, 1764, 6084,  289,  841, 1521,   25, 6241, 1936,    9,  784,
       3136, 1936, 4096,  289,   16, 3721])>

In [105]:
# tf.sqrt(X)
# # Produces InvalidArgumentError
# # Value for attr 'T' of int64 is not in the list of allowed values:
# # bfloat16, half, float, double, complex64, complex128

In [106]:
X = tf.cast(X, dtype=tf.float32)
tf.sqrt(X)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([1.4142135, 5.656854 , 9.899495 , 8.246211 , 2.6457512, 2.828427 ,
       5.       , 9.327379 , 7.1414285, 7.745967 , 6.78233  , 8.3666   ,
       8.83176  , 4.472136 , 1.7320508, 8.062258 , 9.69536  , 5.8309517,
       7.745967 , 2.828427 , 4.690416 , 8.602325 , 4.690416 , 3.1622777,
       8.774964 , 7.6811457, 3.3166249, 9.949874 , 6.928203 , 6.3245554,
       9.380832 , 5.3851647, 9.486833 , 8.185352 , 6.4807405, 8.83176  ,
       4.1231055, 5.3851647, 6.244998 , 2.236068 , 8.888194 , 6.6332498,
       1.7320508, 5.2915025, 7.483315 , 6.6332498, 8.       , 4.1231055,
       2.       , 7.81025  ], dtype=float32)>

In [107]:
tf.math.log(X)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6931472, 3.465736 , 4.5849676, 4.2195077, 1.9459102, 2.0794415,
       3.218876 , 4.465908 , 3.9318256, 4.0943446, 3.8286414, 4.248495 ,
       4.356709 , 2.9957323, 1.0986123, 4.1743875, 4.543295 , 3.5263605,
       4.0943446, 2.0794415, 3.0910425, 4.304065 , 3.0910425, 2.3025851,
       4.3438053, 4.0775375, 2.3978953, 4.59512  , 3.871201 , 3.6888795,
       4.477337 , 3.3672957, 4.4998097, 4.204693 , 3.7376697, 4.356709 ,
       2.8332133, 3.3672957, 3.6635616, 1.609438 , 4.3694477, 3.7841897,
       1.0986123, 3.3322046, 4.0253515, 3.7841897, 4.158883 , 2.8332133,
       1.3862944, 4.1108737], dtype=float32)>

In [97]:
#tf.squeeze() - remove all dimensions of 1 from a tensor
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[32, 89,  8, 28, 43, 83, 23, 74, 38, 64, 26, 85, 93, 74, 40,
            9, 79, 53, 78, 27, 21, 11, 13, 89, 72,  8, 37, 22, 82, 88,
           56, 70, 59, 29, 63, 76, 52, 30, 87, 29, 79, 32, 47, 54, 67,
           43, 75, 54, 11,  2]]]]])>

In [98]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [99]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 89,  8, 28, 43, 83, 23, 74, 38, 64, 26, 85, 93, 74, 40,  9, 79,
       53, 78, 27, 21, 11, 13, 89, 72,  8, 37, 22, 82, 88, 56, 70, 59, 29,
       63, 76, 52, 30, 87, 29, 79, 32, 47, 54, 67, 43, 75, 54, 11,  2])>

In [100]:
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

One-hot encoding

In [101]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [102]:
tf.one_hot(some_list, depth=4, on_value=5, off_value=3)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[5, 3, 3, 3],
       [3, 5, 3, 3],
       [3, 3, 5, 3],
       [3, 3, 3, 5]], dtype=int32)>

Thank you